1、做了环境切换的测试。
参考 http://m.blog.csdn.net/article/details?id=52013537
2、加了事务的处理
一个事务里方法有异常抛出来，则都回滚。
Service A，B
A有事务，A调用B，
    1.1、如果B没有事务，B内不是原子操作，A 吞掉B异常后，只要不抛出来，A的事务不回滚。
    1.2、如果B加入了A的事务，B有异常，不管A是否有Catch，事务都会回滚。因为A,B是同一个事务
    1.3、如果B开启新事务,B内是原子操作，A 吞掉B异常后，只要不抛出来，A的事务不回滚